/*
 * Dive EA REST API
 * Dive Experience Amplifier REST API provides a set of services which leverage obtaining catalog and TV grid info, contextual items (cards) information and saving and a static (scene by scene) version of the card carousel for linear TV and video on demand
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
 
package com.touchvie.sdk.api; 
 
import com.touchvie.sdk.ApiException; 
import com.touchvie.sdk.ApiCallback; 
import com.touchvie.sdk.model.*; 
import com.touchvie.sdk.Pair; 
 
import com.touchvie.sdk.model.AccessToken; 
import com.touchvie.sdk.model.AuthError; 
import com.touchvie.sdk.model.Card; 
import com.touchvie.sdk.model.ChannelStatus; 
import com.touchvie.sdk.model.MovieStatus; 
import com.touchvie.sdk.model.TvGrid; 
 
 
import java.util.ArrayList; 
import java.util.HashMap; 
import java.util.List; 
import java.util.Map; 
 
 
public interface InterfaceApi { 
 
    public com.squareup.okhttp.Call deleteLikesAsync(String authorization, String cardId, String acceptLanguage, final ApiCallback<Void> callback) throws ApiException;
    public com.squareup.okhttp.Call getCardAsync(String authorization, String cardId, String acceptLanguage, Boolean products, Boolean userData, String imageSize, final ApiCallback<Card> callback) throws ApiException;
    public com.squareup.okhttp.Call getCardVersionAsync(String authorization, String cardId, String version, String acceptLanguage, Boolean products, Boolean userData, Boolean relations, String imageSize, final ApiCallback<Card> callback) throws ApiException;
    public com.squareup.okhttp.Call getCatalogMovieAsync(String authorization, String clientMovieId, String acceptLanguage, String imageSize, final ApiCallback<Card> callback) throws ApiException;
    public com.squareup.okhttp.Call getChannelGridAsync(String authorization, String channelId, String acceptLanguage, String imageSize, final ApiCallback<TvGrid> callback) throws ApiException;
    public com.squareup.okhttp.Call getChannelMovieAsync(String authorization, String channelId, String acceptLanguage, String imageSize, final ApiCallback<Card> callback) throws ApiException;
    public com.squareup.okhttp.Call getLikesAsync(String authorization, String acceptLanguage, String imageSize, String paginateKey, String size, final ApiCallback<List<Card>> callback) throws ApiException;
    public com.squareup.okhttp.Call getReadyChannelsAsync(String authorization, List<String> channelIdList, String acceptLanguage, final ApiCallback<List<ChannelStatus>> callback) throws ApiException;
    public com.squareup.okhttp.Call getReadyMoviesAsync(String authorization, List<String> clientMovieIdList, String acceptLanguage, final ApiCallback<List<MovieStatus>> callback) throws ApiException;
    public com.squareup.okhttp.Call getStaticChannelSceneAsync(String authorization, String channelId, String acceptLanguage, Boolean relations, String imageSize, final ApiCallback<List<Card>> callback) throws ApiException;
    public com.squareup.okhttp.Call getStaticMovieSceneAsync(String authorization, String clientMovieId, Float timestamp, String acceptLanguage, Boolean relations, String imageSize, final ApiCallback<List<Card>> callback) throws ApiException;
    public com.squareup.okhttp.Call postLikesAsync(String authorization, String cardId, String acceptLanguage, final ApiCallback<Void> callback) throws ApiException;
    
 
} 
