/*
 * Dive EA REST API
 * Dive Experience Amplifier REST API provides a set of services which leverage obtaining catalog and TV grid info, contextual items (cards) information and saving and a static (scene by scene) version of the card carousel for linear TV and video on demand
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package com.touchvie.sdk.model;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.io.Serializable;

/**
 * Dive interactive capabilities of this catalog item
 */
@ApiModel(description = "Dive interactive capabilities of this catalog item")

public class CatalogSync implements Serializable {
  private static final long serialVersionUID = 1L;

  @SerializedName("is_synchronizable")
  private Boolean isSynchronizable = null;

  public CatalogSync isSynchronizable(Boolean isSynchronizable) {
    this.isSynchronizable = isSynchronizable;
    return this;
  }

   /**
   * Indicates if this catalog item can be synchronized
   * @return isSynchronizable
  **/
  @ApiModelProperty(required = true, value = "Indicates if this catalog item can be synchronized")
  public Boolean getIsSynchronizable() {
    return isSynchronizable;
  }

  public void setIsSynchronizable(Boolean isSynchronizable) {
    this.isSynchronizable = isSynchronizable;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    CatalogSync catalogSync = (CatalogSync) o;
    return Objects.equals(this.isSynchronizable, catalogSync.isSynchronizable);
  }

  @Override
  public int hashCode() {
    return Objects.hash(isSynchronizable);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class CatalogSync {\n");
    
    sb.append("    isSynchronizable: ").append(toIndentedString(isSynchronizable)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
  
}

