/*
 * Dive EA REST API
 * Dive Experience Amplifier REST API provides a set of services which leverage obtaining catalog and TV grid info, contextual items (cards) information and saving and a static (scene by scene) version of the card carousel for linear TV and video on demand
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package com.touchvie.sdk.model;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import com.touchvie.sdk.model.DupleData;
import com.touchvie.sdk.model.RelationModule;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;
import java.io.Serializable;

/**
 * List of related pairs of cards, each pair having a relationship type between both cards
 */
@ApiModel(description = "List of related pairs of cards, each pair having a relationship type between both cards")

public class Duple extends RelationModule implements Serializable {
  private static final long serialVersionUID = 1L;

  /**
   * Duple module content type, defines what kind of relations are contained in the module
   */
  @JsonAdapter(ContentTypeEnum.Adapter.class)
  public enum ContentTypeEnum {
    MOVIE_LOCATIONS("movie_locations"),
    
    WORN_BY("worn_by"),
    
    CASTING("casting"),
    
    CASTING_FASHION("casting_fashion"),
    
    FILMOGRAPHY("filmography"),
    
    PLAYED_BY("played_by"),
    
    FEATURED_IN("featured_in"),
    
    TEST("test");

    private String value;

    ContentTypeEnum(String value) {
      this.value = value;
    }

    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }

    public static ContentTypeEnum fromValue(String text) {
      for (ContentTypeEnum b : ContentTypeEnum.values()) {
        if (String.valueOf(b.value).equals(text)) {
          return b;
        }
      }
      return null;
    }

    public static class Adapter extends TypeAdapter<ContentTypeEnum> {
      @Override
      public void write(final JsonWriter jsonWriter, final ContentTypeEnum enumeration) throws IOException {
        jsonWriter.value(enumeration.getValue());
      }

      @Override
      public ContentTypeEnum read(final JsonReader jsonReader) throws IOException {
        String value = jsonReader.nextString();
        return ContentTypeEnum.fromValue(String.valueOf(value));
      }
    }
  }

  @SerializedName("content_type")
  private ContentTypeEnum contentType = null;

  @SerializedName("data")
  private List<DupleData> data = new ArrayList<DupleData>();

  public Duple contentType(ContentTypeEnum contentType) {
    this.contentType = contentType;
    return this;
  }

   /**
   * Duple module content type, defines what kind of relations are contained in the module
   * @return contentType
  **/
  @ApiModelProperty(required = true, value = "Duple module content type, defines what kind of relations are contained in the module")
  public ContentTypeEnum getContentType() {
    return contentType;
  }

  public void setContentType(ContentTypeEnum contentType) {
    this.contentType = contentType;
  }

  public Duple data(List<DupleData> data) {
    this.data = data;
    return this;
  }

  public Duple addDataItem(DupleData dataItem) {
    this.data.add(dataItem);
    return this;
  }

   /**
   * Get data
   * @return data
  **/
  @ApiModelProperty(required = true, value = "")
  public List<DupleData> getData() {
    return data;
  }

  public void setData(List<DupleData> data) {
    this.data = data;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    Duple duple = (Duple) o;
    return Objects.equals(this.contentType, duple.contentType) &&
        Objects.equals(this.data, duple.data) &&
        super.equals(o);
  }

  @Override
  public int hashCode() {
    return Objects.hash(contentType, data, super.hashCode());
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class Duple {\n");
    sb.append("    ").append(toIndentedString(super.toString())).append("\n");
    sb.append("    contentType: ").append(toIndentedString(contentType)).append("\n");
    sb.append("    data: ").append(toIndentedString(data)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
  
}

