/*
 * Dive EA REST API
 * Dive Experience Amplifier REST API provides a set of services which leverage obtaining catalog and TV grid info, contextual items (cards) information and saving and a static (scene by scene) version of the card carousel for linear TV and video on demand
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package com.touchvie.sdk.model;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import com.touchvie.sdk.model.Card;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.io.Serializable;

/**
 * DupleData
 */

public class DupleData implements Serializable {
  private static final long serialVersionUID = 1L;

  @SerializedName("rel_type")
  private String relType = null;

  @SerializedName("from")
  private Card from = null;

  @SerializedName("to")
  private Card to = null;

  public DupleData relType(String relType) {
    this.relType = relType;
    return this;
  }

   /**
   * Indicates the relationship between the pair of cards (from &gt; rel_type &gt; to)
   * @return relType
  **/
  @ApiModelProperty(required = true, value = "Indicates the relationship between the pair of cards (from > rel_type > to)")
  public String getRelType() {
    return relType;
  }

  public void setRelType(String relType) {
    this.relType = relType;
  }

  public DupleData from(Card from) {
    this.from = from;
    return this;
  }

   /**
   * Get from
   * @return from
  **/
  @ApiModelProperty(required = true, value = "")
  public Card getFrom() {
    return from;
  }

  public void setFrom(Card from) {
    this.from = from;
  }

  public DupleData to(Card to) {
    this.to = to;
    return this;
  }

   /**
   * Get to
   * @return to
  **/
  @ApiModelProperty(value = "")
  public Card getTo() {
    return to;
  }

  public void setTo(Card to) {
    this.to = to;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    DupleData dupleData = (DupleData) o;
    return Objects.equals(this.relType, dupleData.relType) &&
        Objects.equals(this.from, dupleData.from) &&
        Objects.equals(this.to, dupleData.to);
  }

  @Override
  public int hashCode() {
    return Objects.hash(relType, from, to);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class DupleData {\n");
    
    sb.append("    relType: ").append(toIndentedString(relType)).append("\n");
    sb.append("    from: ").append(toIndentedString(from)).append("\n");
    sb.append("    to: ").append(toIndentedString(to)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
  
}

