/*
 * Dive EA REST API
 * Dive Experience Amplifier REST API provides a set of services which leverage obtaining catalog and TV grid info, contextual items (cards) information and saving and a static (scene by scene) version of the card carousel for linear TV and video on demand
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package com.touchvie.sdk.model;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.io.Serializable;

/**
 * ListingData
 */

public class ListingData implements Serializable {
  private static final long serialVersionUID = 1L;

  @SerializedName("text")
  private String text = null;

  @SerializedName("value")
  private String value = null;

  public ListingData text(String text) {
    this.text = text;
    return this;
  }

   /**
   * Item label
   * @return text
  **/
  @ApiModelProperty(required = true, value = "Item label")
  public String getText() {
    return text;
  }

  public void setText(String text) {
    this.text = text;
  }

  public ListingData value(String value) {
    this.value = value;
    return this;
  }

   /**
   * Item value
   * @return value
  **/
  @ApiModelProperty(required = true, value = "Item value")
  public String getValue() {
    return value;
  }

  public void setValue(String value) {
    this.value = value;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ListingData listingData = (ListingData) o;
    return Objects.equals(this.text, listingData.text) &&
        Objects.equals(this.value, listingData.value);
  }

  @Override
  public int hashCode() {
    return Objects.hash(text, value);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ListingData {\n");
    
    sb.append("    text: ").append(toIndentedString(text)).append("\n");
    sb.append("    value: ").append(toIndentedString(value)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
  
}

