/*
 * Dive EA REST API
 * Dive Experience Amplifier REST API provides a set of services which leverage obtaining catalog and TV grid info, contextual items (cards) information and saving and a static (scene by scene) version of the card carousel for linear TV and video on demand
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package com.touchvie.sdk.model;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import com.touchvie.sdk.model.ImageData;
import com.touchvie.sdk.model.SeasonsChapters;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;
import java.io.Serializable;

/**
 * SeasonsData
 */

public class SeasonsData implements Serializable {
  private static final long serialVersionUID = 1L;

  @SerializedName("season_index")
  private Integer seasonIndex = null;

  @SerializedName("creators")
  private String creators = null;

  @SerializedName("image")
  private ImageData image = null;

  @SerializedName("year")
  private Integer year = null;

  @SerializedName("chapters")
  private List<SeasonsChapters> chapters = new ArrayList<SeasonsChapters>();

  public SeasonsData seasonIndex(Integer seasonIndex) {
    this.seasonIndex = seasonIndex;
    return this;
  }

   /**
   * Index of the season
   * @return seasonIndex
  **/
  @ApiModelProperty(required = true, value = "Index of the season")
  public Integer getSeasonIndex() {
    return seasonIndex;
  }

  public void setSeasonIndex(Integer seasonIndex) {
    this.seasonIndex = seasonIndex;
  }

  public SeasonsData creators(String creators) {
    this.creators = creators;
    return this;
  }

   /**
   * Comma separated list of season creators
   * @return creators
  **/
  @ApiModelProperty(required = true, value = "Comma separated list of season creators")
  public String getCreators() {
    return creators;
  }

  public void setCreators(String creators) {
    this.creators = creators;
  }

  public SeasonsData image(ImageData image) {
    this.image = image;
    return this;
  }

   /**
   * Get image
   * @return image
  **/
  @ApiModelProperty(required = true, value = "")
  public ImageData getImage() {
    return image;
  }

  public void setImage(ImageData image) {
    this.image = image;
  }

  public SeasonsData year(Integer year) {
    this.year = year;
    return this;
  }

   /**
   * Year of production of this season
   * @return year
  **/
  @ApiModelProperty(required = true, value = "Year of production of this season")
  public Integer getYear() {
    return year;
  }

  public void setYear(Integer year) {
    this.year = year;
  }

  public SeasonsData chapters(List<SeasonsChapters> chapters) {
    this.chapters = chapters;
    return this;
  }

  public SeasonsData addChaptersItem(SeasonsChapters chaptersItem) {
    this.chapters.add(chaptersItem);
    return this;
  }

   /**
   * List of season chapters
   * @return chapters
  **/
  @ApiModelProperty(required = true, value = "List of season chapters")
  public List<SeasonsChapters> getChapters() {
    return chapters;
  }

  public void setChapters(List<SeasonsChapters> chapters) {
    this.chapters = chapters;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    SeasonsData seasonsData = (SeasonsData) o;
    return Objects.equals(this.seasonIndex, seasonsData.seasonIndex) &&
        Objects.equals(this.creators, seasonsData.creators) &&
        Objects.equals(this.image, seasonsData.image) &&
        Objects.equals(this.year, seasonsData.year) &&
        Objects.equals(this.chapters, seasonsData.chapters);
  }

  @Override
  public int hashCode() {
    return Objects.hash(seasonIndex, creators, image, year, chapters);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class SeasonsData {\n");
    
    sb.append("    seasonIndex: ").append(toIndentedString(seasonIndex)).append("\n");
    sb.append("    creators: ").append(toIndentedString(creators)).append("\n");
    sb.append("    image: ").append(toIndentedString(image)).append("\n");
    sb.append("    year: ").append(toIndentedString(year)).append("\n");
    sb.append("    chapters: ").append(toIndentedString(chapters)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
  
}

