/*
 * Dive EA REST API
 * Dive Experience Amplifier REST API provides a set of services which leverage obtaining catalog and TV grid info, contextual items (cards) information and saving and a static (scene by scene) version of the card carousel for linear TV and video on demand
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package com.touchvie.sdk.model;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import com.touchvie.sdk.model.Card;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.io.Serializable;

/**
 * TV event information
 */
@ApiModel(description = "TV event information")

public class TvEvent implements Serializable {
  private static final long serialVersionUID = 1L;

  @SerializedName("channel_id")
  private String channelId = null;

  @SerializedName("channel_name")
  private String channelName = null;

  @SerializedName("start_date")
  private Long startDate = null;

  @SerializedName("end_date")
  private Long endDate = null;

  @SerializedName("card")
  private Card card = null;

  public TvEvent channelId(String channelId) {
    this.channelId = channelId;
    return this;
  }

   /**
   * TV channel ID where the the event is schedulled
   * @return channelId
  **/
  @ApiModelProperty(required = true, value = "TV channel ID where the the event is schedulled")
  public String getChannelId() {
    return channelId;
  }

  public void setChannelId(String channelId) {
    this.channelId = channelId;
  }

  public TvEvent channelName(String channelName) {
    this.channelName = channelName;
    return this;
  }

   /**
   * TV channel name
   * @return channelName
  **/
  @ApiModelProperty(required = true, value = "TV channel name")
  public String getChannelName() {
    return channelName;
  }

  public void setChannelName(String channelName) {
    this.channelName = channelName;
  }

  public TvEvent startDate(Long startDate) {
    this.startDate = startDate;
    return this;
  }

   /**
   * TV event start date in milliseconds since EPOCH
   * @return startDate
  **/
  @ApiModelProperty(required = true, value = "TV event start date in milliseconds since EPOCH")
  public Long getStartDate() {
    return startDate;
  }

  public void setStartDate(Long startDate) {
    this.startDate = startDate;
  }

  public TvEvent endDate(Long endDate) {
    this.endDate = endDate;
    return this;
  }

   /**
   * TV event end date in milliseconds since EPOCH
   * @return endDate
  **/
  @ApiModelProperty(required = true, value = "TV event end date in milliseconds since EPOCH")
  public Long getEndDate() {
    return endDate;
  }

  public void setEndDate(Long endDate) {
    this.endDate = endDate;
  }

  public TvEvent card(Card card) {
    this.card = card;
    return this;
  }

   /**
   * Associated content (movie or chapter) card
   * @return card
  **/
  @ApiModelProperty(required = true, value = "Associated content (movie or chapter) card")
  public Card getCard() {
    return card;
  }

  public void setCard(Card card) {
    this.card = card;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    TvEvent tvEvent = (TvEvent) o;
    return Objects.equals(this.channelId, tvEvent.channelId) &&
        Objects.equals(this.channelName, tvEvent.channelName) &&
        Objects.equals(this.startDate, tvEvent.startDate) &&
        Objects.equals(this.endDate, tvEvent.endDate) &&
        Objects.equals(this.card, tvEvent.card);
  }

  @Override
  public int hashCode() {
    return Objects.hash(channelId, channelName, startDate, endDate, card);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class TvEvent {\n");
    
    sb.append("    channelId: ").append(toIndentedString(channelId)).append("\n");
    sb.append("    channelName: ").append(toIndentedString(channelName)).append("\n");
    sb.append("    startDate: ").append(toIndentedString(startDate)).append("\n");
    sb.append("    endDate: ").append(toIndentedString(endDate)).append("\n");
    sb.append("    card: ").append(toIndentedString(card)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
  
}

