/*
 * Dive EA REST API
 * Dive Experience Amplifier REST API provides a set of services which leverage obtaining catalog and TV grid info, contextual items (cards) information and saving and a static (scene by scene) version of the card carousel for linear TV and video on demand
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package com.touchvie.sdk.model;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import com.touchvie.sdk.model.TvEvent;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;

/**
 * TV grid information
 */
@ApiModel(description = "TV grid information")
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2017-11-23T13:15:20.476+01:00")
public class TvGrid {
  @SerializedName("broadcast")
  private List<TvEvent> broadcast = new ArrayList<TvEvent>();

  @SerializedName("upcoming")
  private List<TvEvent> upcoming = new ArrayList<TvEvent>();

  public TvGrid broadcast(List<TvEvent> broadcast) {
    this.broadcast = broadcast;
    return this;
  }

  public TvGrid addBroadcastItem(TvEvent broadcastItem) {
    this.broadcast.add(broadcastItem);
    return this;
  }

   /**
   * List of TV events currently being broadcasted
   * @return broadcast
  **/
  @ApiModelProperty(required = true, value = "List of TV events currently being broadcasted")
  public List<TvEvent> getBroadcast() {
    return broadcast;
  }

  public void setBroadcast(List<TvEvent> broadcast) {
    this.broadcast = broadcast;
  }

  public TvGrid upcoming(List<TvEvent> upcoming) {
    this.upcoming = upcoming;
    return this;
  }

  public TvGrid addUpcomingItem(TvEvent upcomingItem) {
    this.upcoming.add(upcomingItem);
    return this;
  }

   /**
   * List of upcoming TV events
   * @return upcoming
  **/
  @ApiModelProperty(required = true, value = "List of upcoming TV events")
  public List<TvEvent> getUpcoming() {
    return upcoming;
  }

  public void setUpcoming(List<TvEvent> upcoming) {
    this.upcoming = upcoming;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    TvGrid tvGrid = (TvGrid) o;
    return Objects.equals(this.broadcast, tvGrid.broadcast) &&
        Objects.equals(this.upcoming, tvGrid.upcoming);
  }

  @Override
  public int hashCode() {
    return Objects.hash(broadcast, upcoming);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class TvGrid {\n");
    
    sb.append("    broadcast: ").append(toIndentedString(broadcast)).append("\n");
    sb.append("    upcoming: ").append(toIndentedString(upcoming)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
  
}

